### ISSUE TITLE
ValueError: Invalid values

### ISSUE THREAD

**Issue by ghost** [LameLemon/GrabIt#2]
```
Traceback (most recent call last):
  File "user/GrabIt/RedditGrabber.py", line 183, in <module>
    main(parser)

  File "user/GrabIt/RedditGrabber.py", line 125, in main
    feeder(subR, parser)

  File "user/GrabIt/RedditGrabber.py", line 83, in feeder
    submission_queue = Reddit(subR, parser).queue()

  File "user/GrabIt/resources/interfaces/reddit.py", line 65, in queue
    submissions = reddit.subreddit(self.subR).controversial(limit=int(posts), time_filter=self.parser.time_filter)

  File "user.local/lib/python3.9/site-packages/praw/models/helpers.py", line 313, in __call__
    return Subreddit(self._reddit, display_name=display_name)

  File "user/.local/lib/python3.9/site-packages/praw/models/reddit/subreddit.py", line 561, in __init__
    super().__init__(reddit, _data=_data)

  File "user/.local/lib/python3.9/site-packages/praw/models/listing/mixins/subreddit.py", line 71, in __init__
    super().__init__(reddit, _data=_data)

  File "user/.local/lib/python3.9/site-packages/praw/models/reddit/base.py", line 65, in __init__
    raise ValueError(

ValueError: An invalid value was specified for display_name. Check that the argument for the display_name parameter is not empty.
```

**Comment by ghost** [comment]
This is the subreddit causing issues from my testing 
https://www.reddit.com/r/unket/
Any other subreddits among the sub list is fine for now!
